### PR TITLE
Feature#5/migrations and models

### PR DESCRIPTION
**Pull request by juperameza**
# Description
 - What?: I've added all the models with them according associations and their migrations except for the user and status
 - Why?: To have the database set up for later issued
 
For mor information see issue #5

### CODE REVIEW

**Review by nallely64 — APPROVED** [review]

**Review by germanruzca — DISMISSED** [review]
LGTM!!🚀

**Review by VictorElizalde — APPROVED** [review]
LGTM

**Review by AlejandroCuriel — APPROVED** [review]
LGTM :rocket: :cupcake:

**Review by germanruzca — APPROVED** [review]

**Review by Javi1499 — APPROVED** [review]
LGTM

**Pull request merged**
