### PR TITLE
Feature#17/configure all migrations

### PR DESCRIPTION
**Pull request by juperameza**
# Description

 - What?: I've finished adding all the foreign keys that was missing from the user and status table 
 - Why?: To leave the database ready for use
 
For mor information see issue #17

### CODE REVIEW

**Review by germanruzca — APPROVED** [review]
LGTM

**Review by YilKanda — APPROVED** [review]
Update your branch with respect to master.

**Review by YilKanda — CHANGES_REQUESTED** [review]
Update your branch with respect to master.

**Review by germanruzca — APPROVED** [review]
LGTM

**Review by VictorElizalde — APPROVED** [review]
LGTM!

**Pull request merged**
