### PR TITLE
Feature#43/implement initial purchase system

### PR DESCRIPTION
**Pull request by EliasUR**
# Description
What did you implemented/Why did you implemented this:
 - Added a method to buy products which create a order with quantity and total amount
 - Added a view to make users know his purchase history
 
  ## Screenshots 

rec-screen

Closes: #43

### CODE REVIEW

**Review by Javi1499 — APPROVED** [review]
Nice job

**Review by germanruzca — APPROVED** [review]
LGTM! 🚀

**Review by juperameza — COMMENTED** [review]
LGTM just resolve conflicts

**Review by germanruzca — APPROVED** [review]
LGTM

**Review by Javi1499 — APPROVED** [review]
LGTM

**Pull request merged**
