### PR TITLE
Feature#61/create pages routes

### PR DESCRIPTION
**Pull request by germanruzca**
# Description
For Notification, Messages and Favorites were created:
- The Route
- The View
- The method of the controller

This PR completes the solution to redirect the user inside the profile private setting and other features.

### CODE REVIEW

**Review by juperameza — DISMISSED** [review]
LGTM!!

**Review by Javi1499 — DISMISSED** [review]
LGTM.

**Review by AlejandroCuriel — DISMISSED** [review]
LGTM 🚀

**Review by nallely64 — APPROVED** [review]
LGTM!

**Review by Javi1499 — APPROVED** [review]
LGTM

**Pull request merged**
