### PR TITLE
Delete status id from permitted params

### PR DESCRIPTION
**Pull request by juperameza**
# Description

 Examples:
 - What?: I've deleted the status id from the permitted params on post controller
 - Why?: I did this in order to add security to the post since the status is something that changes automatically without the user knowledge
 
For more information see issue #29

### CODE REVIEW

**Review by EliasUR — DISMISSED** [review]
LGTM

**Review by germanruzca — APPROVED** [review]
Good

**Review by EliasUR — APPROVED** [review]
LGTM 2.0

**Review by Javi1499 — APPROVED** [review]
LGTM

**Pull request merged**
